pull_request_rules:
  - name: Auto-close PRs on stable branch
    conditions:
      - and:
        - and:
          - author!=surajshetty3416
          - author!=deepeshgarg007
          - author!=ankush
          - author!=frappe-pr-bot
          - author!=mergify[bot]
        - or:
          - base=version-15
          - base=version-14
          - base=version-13
          - base=version-12
    actions:
      close:
      comment:
          message: |
            @{{author}}, thanks for the contribution, but we do not accept pull requests on a stable branch. Please raise PR on an appropriate hotfix branch.
            https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist#which-branch

  - name: backport to develop
    conditions:
      - label="backport develop"
    actions:
      backport:
        branches:
          - develop
        assignees:
          - "{{ author }}"

  - name: backport to version-13-hotfix
    conditions:
      - label="backport version-13-hotfix"
    actions:
      backport:
        branches:
          - version-13-hotfix
        assignees:
          - "{{ author }}"

  - name: backport to version-14-hotfix
<<<<<<< HEAD
    conditions:
      - label="backport version-14-hotfix"
    actions:
      backport:
        branches:
          - version-14-hotfix
        assignees:
          - "{{ author }}"

  - name: backport to develop
    conditions:
      - label="backport develop"
    actions:
      backport:
        branches:
          - develop
        assignees:
          - "{{ author }}"

  - name: backport to version-13-pre-release
=======
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 53615bb31040628756ac2b31ed112197ce976581
=======
>>>>>>> fc1c3f895a2bbd99dd7a0574de180a4095b6e41b
>>>>>>> b4ee936175174b0954ceee845039d7e9c9e808df
=======
>>>>>>> e4a2b8db38691ac78018fd51fe0e037afbd14d87
>>>>>>> 61099500f6f137a058d07823f121b41b3ad85b02
    conditions:
      - label="backport version-14-hotfix"
    actions:
      backport:
        branches:
          - version-14-hotfix
        assignees:
          - "{{ author }}"

